### ISSUE TITLE
More wallets to add

### ISSUE THREAD

**Issue by Bosch-0** [sbddesign/bip21-site#11]
Need to add lots of the wallets listed here: https://bitcoinops.org/en/compatibility/

Also love the detail they go into with each wallet (click on the wallet name to see an in-depth comparability analysis. Maybe something this campaign can do?

**Comment by sbddesign** [comment]
> Need to add lots of the wallets listed here: https://bitcoinops.org/en/compatibility/

@Bosch-0 There are a lot of wallets here. I suspect most of these wallets and services are on-chain only. Not a problem, but it basically means we're checking all of these merely for BIP21 support and not necessarily support of the `lightning` param. 

How would you feel about us simply adding these as issues? My thinking being that there are a lot of bitcoin wallets in existence. If we create them as issues, then the website isn't filled with an overwhelming table full of question marks until we get them all tested. People who have access to these wallets and services can respond directly to the issue.

> Also love the detail they go into with each wallet (click on the wallet name to see an in-depth comparability analysis. Maybe something this campaign can do?

I don't think I want to replicate the info they are talking about there, to avoid redundancy and because I don't think most of their information is relevant to the scope of this project. Is there specific information relating to BIP21 QRs with lightning params that you feel needs to be documented with the wallets we test?

**Comment by Bosch-0** [comment]
Yeah totally! Listing all of them probably isn't necessary. Just wanted to put this here as a good starting point as to where to start looking.

Also here is more 😆 https://lightningnetworkstores.com/wallets

> I don't think I want to replicate the info they are talking about there, to avoid redundancy and because I don't think most of their information is relevant to the scope of this project. Is there specific information relating to BIP21 QRs with lightning params that you feel needs to be documented with the wallets we test?

Unsure yet, probably better to see if devs would find this valuable. This campaign is a little more simple on the implementation side so probably isn't necessary to go into that depth

**Comment by sbddesign** [comment]
I have opened individual issues for _most_ of the wallets from the OpTech list. I omitted some:

- Bitcoin Core Wallet - doesn't scan QRs; not typically used as a wallet, IMO.
- Bitcoin Wallet - couldn't find a website for this project that didn't come across sketch af.
- BitGo - seems institutional only, and no indication of LN support.
- BlockSettle - seems very Liquid focused, not really the same use case as what we're doing
- Copay - seems like this became the BitPay wallet, which has already been tested
- Electrum - as a desktop wallet, not sure that it interacts with QR codes frequently (if at all)
- OpenDime - not sure this is applicable as a novel hardware key device
- Also omitted CashApp, Samourai, and several others that we already tested

Aside from that, issues #20 - #38 are all from the OpTech list. @Bosch-0 How do you feel about this? Can we close this issue?

**Comment by Bosch-0** [comment]
Yep that looks fine to me, closing :)
