### ISSUE TITLE
iPhone 8

### ISSUE THREAD

**Issue by pavlenex** [sbddesign/bip21-site#54]
### Hardware Name

iPhone 8

### Scans BIP-21

Yes

### Description

Scans well.

**Comment by sbddesign** [comment]
Hey @pavlenex do you remember which app you were using when you did this test?

**Comment by pavlenex** [comment]
I was just using phone camera, it opened a Blue Wallet ,does it really matter which app is used?

**Comment by sbddesign** [comment]
> does it really matter which app is used?

Well, we won't know for sure until we collect that data. I have personally witnessed situations where you have a device with a camera and one app scans QRs very well and another app scans QRs very poorly. So instead of saying "this device has a bad camera", I think we must first verify how the camera is being utilized; therefore, I like to track which app a piece of hardware was tested with.
